### ISSUE TITLE
customized seeds

### ISSUE THREAD

**Issue by sallywang147** [uni-due-syssec/efcf-framework#7]
Hi, thank you for the great work! I'm trying to run the fuzzer with my customized seeds. I know EFCF enables --seed-files for  specific seed files, but what are the expected format of each seed, i.e. how can we specify the input value of each function as a seed? Thanks for your help.

**Comment by f0rki** [comment]
EF/CF uses a custom binary format to store generated test cases (=> sequences of transactions). So to provide custom seeds you need to provide files in that custom format to EF/CF. The binary format is quite underdocumented (aka. read-the-code) and not nice to work with, so we have a converter to/from yaml: the `efuzzcasetranscoder` tool (see also the [ethmutator repo readme](https://github.com/uni-due-syssec/efcf-ethmutator/tree/84d3a0e61c4269e3bdf3d231e114f75442027a98#fuzzcase-transcoder)). So I would recommend writing the custom seeds as yaml files, convert them to the binary format using the transcoder tool and provide that via `--seed-files`.

You can view an example of the yaml format here: [examples/ReentrancyVulnBankBuggyLockHard/attack.efcf.yml](https://github.com/uni-due-syssec/efcf-framework/blob/main/examples/ReentrancyVulnBankBuggyLockHard/attack.efcf.yml)

Note that in this format, you still need to manually encode the input according to the contract's ABI. There are many tools out there, but I have used the [ethabi cli](https://github.com/rust-ethereum/ethabi) in the past. However, this seems to be unmaintained, so I think you might want to find other alternatives.

If you want to provide arguments for multiple separate function calls, I suggest you create one test case file per function call, i.e., a transaction sequence with a single transaction. Then EF/CF will pick them up and combine them in arbitary orders. If you put all function calls into a single file, EF/CF will discard the functions after the first transactions that reverts, so you might loose some parts of your seeds.

**Comment by sallywang147** [comment]
Thanks very much!

**Comment by f0rki** [comment]
no problem.
